"""Added catalog item and brand

Revision ID: 94275fbd8d10
Revises: f08f83974b20
Create Date: 2022-01-06 17:42:32.182812

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '94275fbd8d10'
down_revision = 'f08f83974b20'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('catalog_brand',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), server_default='False', nullable=False),
    sa.Column('brand', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('catalog_item',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), server_default='False', nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=False),
    sa.Column('price', sa.Float(), nullable=True),
    sa.Column('catalog_type_id', sa.Integer(), nullable=False),
    sa.Column('brand_id', sa.Integer(), nullable=False),
    sa.Column('available_stock', sa.Integer(), nullable=True),
    sa.Column('max_stock', sa.Integer(), nullable=True),
    sa.Column('restock_threshold', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['brand_id'], ['catalog_brand.id'], ),
    sa.ForeignKeyConstraint(['catalog_type_id'], ['catalog_type.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('catalog_item')
    op.drop_table('catalog_brand')
    # ### end Alembic commands ###
